# Use the official MongoDB image
FROM mongo:latest

# Create a directory for storing audio files
# RUN mkdir -p /data/audio
# COPY audio/ /data/audio/

# Copy initialization script to set up admin user and authentication
# COPY ./init-mongo.js /docker-entrypoint-initdb.d/

# artist track path album selection